### ISSUE TITLE
These are great! Add img2img batch controlnet? + any other useful workflows that are simple and are popular 

### ISSUE THREAD

**Issue by FemBoxbrawl** [pwillia7/Basic_ComfyUI_Workflows#1]
Thanks for making these, please add img2img batch (+ controlnet), and any other new workflows you figure out along the way, thank you so much. I am using this with stable swarm UI. my SD forge started lagging and does not even generate imgs anymore, so ill switch to this. thanks again

**Comment by FemBoxbrawl** [comment]
oh and maybe also multi controlnet

**Comment by pwillia7** [comment]
Hey -- Thank you!

Multi controlnet is added now. 

Am planning on building out more txt2img and img2img common workflows in their own folders and will do a batch one. 

You could set this up now with the prompts from file workflow fairly easily if you want to.

**Comment by FemBoxbrawl** [comment]
> Hey -- Thank you!
> 
> Multi controlnet is added now.
> 
> Am planning on building out more txt2img and img2img common workflows in their own folders and will do a batch one.
> 
> You could set this up now with the prompts from file workflow fairly easily if you want to.


Thanks for all of your hard work! This makes life way easier, I was wondering if you could maybe add Inpaint Sketch? that would be great.

(I havent checked out every single one yet, but incase you havent, CN scribble? or i can maybe figure that out by myself)
